### PR TITLE
day-5 HW

### PR DESCRIPTION
**Pull request by AceelAlArifi**
it was so confusing I reached a friend for help..

### CODE REVIEW

**Comment by AceelAlArifi** [comment]
Thanks for the honest feedback, It’s highly appreciated..
Wallah,I tried for more than 6 hours, but I couldn’t.. 
I am still trying to learn how to code..

**Comment by alanoud-GA** [comment]
Even if you didn't manage to solve the problem, it's okay. Next time, submit your code even if it has errors or is missing a few details. I like to see thought process (write your pseudocode and breakdown of the problem in the comments), that way we can figure out what went wrong and needs improvement together 👍 

You will learn with more time and practice. Don't worry.

**Comment by AceelAlArifi** [comment]
Thanks a lot for ur understanding ♥️..

**Comment by AceelAlArifi** [comment]
I’ll try my best inshallah..

**Pull request closed without merging**
